export const actionTypes = {
  SET_PRODUCT: "SET_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  FILTER_PRODUCT: "FILTER_PRODUCT",
  REVOME_SELECTED_PRODUCT: "REVOME_SELECTED_PRODUCT",

  ADD_CART: "ADD_CART",
  DELETE_CART: "DELETE_CART",
  REMOVE_ALL_CART: "REMOVE_ALL_CART",
};
