export const actionTypes = {
  SET_PRODUCT: "SET_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  FILTER_PRODUCT: "FILTER_PRODUCT",
  REVOME_SELECTED_PRODUCT: "REVOME_SELECTED_PRODUCT",

  ADD_TO_CART: "ADD_TO_CART",
  DELETE_CART: "DELETE_CART",
  REMOVE_ALL_CART: "REMOVE_ALL_CART",
  INC_CART: "INC_CART",
  DEC_CART: "DEC_CART",
};
